networks:
  mynetwork:
    driver: bridge
services:
  server-mysql:
    image: mysql:latest
    volumes:
      - ./mysql_data:/var/lib/mysql_data   
      - ./mysql_data/migrate-v001.sql:/docker-entrypoint-initdb.d/migrate-v001.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    command: ["--init-file", "/docker-entrypoint-initdb.d/migrate-v001.sql"]
  python-server:
    image: python-mysql
    volumes:
      - ./python-server:/python-server
    build:
      context: .
      dockerfile: ./python-server/DockerfilePython
    environment:
      MYSQL_HOST: server-mysql
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PORT: 3306
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - server-mysql
    command: ["sh", "-c", "wait-for-it server-mysql:3306 --timeout=30; uvicorn main:app --host 0.0.0.0 --port 8000"]
  react:
    image: react
    build:
      context: ./my-app
      dockerfile: ./DockerfileReact
    environment:
      - REACT_APP_SERVER_PORT=8000
    ports:
      - 3000:3000
    networks:
      - mynetwork    
    volumes:
      - ./my-app:/app
      - /app/node_modules
    depends_on:
      - python-server
    command: npm start
