services:  
  mysql:
    image: mysql:latest
    volumes:
      - ./mysql_data:/var/lib/mysql_data   
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
    ports:
      - "3306:3306"
  python-server:
    image: python-mysql
    volumes:
      - ./python-server:/python-server
    build:
      context: .
      dockerfile: ./python-server/DockerfilePython
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: uvicorn main:app --host
  react:
    image: react
    build:
      context: ./my-app
      dockerfile: ./DockerfileReact
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_PORT=8000
    volumes:
      - ./my-app:/app
      - /app/node_modules
    depends_on:
      - python-server
    command: npm start