version: "3.1"

services:
  mysql:
    image: mysql:latest
    volumes:
      - ./sqlfiles:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"

  python-server:
    image: python-mysql
    volumes:
      - ./python-server:/python-server
    build:
      context: .
      dockerfile: ./server/DockerfilePython
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: python server.py

  react:
    image: react
    build:
      context: ./my-app
      dockerfile: ./DockerfileReact
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_PORT=8000
    volumes:
      - ./my-app:/app
      - /app/node_modules
    command: npm start
