version: "3.1"

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongofiles/:/docker-entrypoint-initdb.d/
    restart: always
    # environment:
    #   #   MONGO_INITDB_ROOT_USERNAME: <admin-user>
    #   #   MONGO_INITDB_ROOT_PASSWORD: <admin-password>
    #   # MONGO_INITDB_DATABASE: mydatabase

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      # ME_CONFIG_MONGODB_ADMINUSERNAME: <admin-user>
      # ME_CONFIG_MONGODB_ADMINPASSWORD: <admin-password>

  server:
    image: nodejs-mongo
    volumes:
      - ./server:/server
      - /server/node_modules
    build:
      context: .
      dockerfile: ./server/DockerfileNodejs
    environment:
      - MONGO_HOST=mongo
      - MONGO_DATABASE
      - SERVER_PASSWORD
      - PORT=8000
      # - MONGO_USER
      # - MONGO_PASS
    ports:
      - 8000:8000
    depends_on:
      - mongo
    command: node server.js

  react:
    image: react
    build:
      context: ./my-app
      dockerfile: ./DockerfileReact
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_PORT=8000
    volumes:
      - ./my-app:/app
      - /app/node_modules
    depends_on:
      - server
    command: npm start
