version: '3.8'
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server
      dockerfile: DockerfilePython
    ports:
      - "5000:5000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"