version: "3.1"

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongofiles/:/docker-entrypoint-initdb.d/
    restart: always

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo

  server:
    image: nodejs-mongo
    volumes:
      - ./server:/server
      - /server/node_modules
    build:
      context: .
      dockerfile: ./server/DockerfileNodejs
    environment:
      - MONGO_HOST=mongo
      - MONGO_DATABASE
      - MONGO_USER
    ports:
      - 8000:8000
    depends_on:
      - mongo
    command: node server.js
