version: "3.8"
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server
      dockerfile: DockerfileNodejs
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - ./mongofiles:/data/db
    ports:
      - "27017:27017"
